[tool.poetry]
name = "walter-quote"
version = "0.1.0"
description = ""
authors = ["Surtains (drooling)"]
readme = "README.md"
packages = [{include = "walter_quote"}]

[tool.poetry.dependencies]
python = "^3.9"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
