WALTER_QUOTES = [
    "“You need to stop focusing on the darkness behind you. The past is the past. Nothing can change what we’ve done.”",
    "“Never give up control. Live life on your own terms.”",
    "“I did it for me. I liked it. I was good at it. And I was really, I was alive.”",
    "“There’s the easy way, and then there’s the right way.”",
    "“You either die a hero or live long enough to see yourself become a villain.”",
    "“I have lived under the threat of death for a year now. And because of that, I’ve made choices.”",
    "“There is gold in the streets just waiting for someone to come and scoop it up.”",
    "“Being the best at something is a very rare thing. You don’t just toss something like that away.”",
    "“I’ve been living with cancer for the better part of a year. Right from the start, it’s a death sentence. That’s what they keep telling me. Well, guess what? Every life comes with a death sentence. So, every few months, I come in here for my regular scan knowing full well that one of these times, hell, maybe even today, I’m gonna hear some bad news. But until then, who’s in charge? Me. That’s how I live my life.”",
    "“If you don’t know who I am, then maybe your best course would be to tread lightly.”",
    "“Jesse, you asked me if I was in the meth business or the money business. Neither. I’m in the empire business.”",
    "“The universe is random. It’s not inevitable. It’s simple chaos. It’s subatomic particles in an endless, aimless collision. That’s what science teaches us, but what is this saying? What is it telling us, when on the very night that this man’s daughter dies, it’s me who’s having a drink with him? How can that be random?”",
    "“I have spent my whole life scared, frightened of things that could happen, might happen, might not happen. Fifty years I spent like that, finding myself awake at three in the morning. But you know what? Ever since my diagnosis, I sleep just fine. What I came to realize is that fear, that’s the worst of it. That’s the real enemy. So, get up, get out in the real world, and you kick that bastard as hard as you can right in the teeth.”",
    "“It’s always been one step forward and two steps back.”",
    "“I told you, Skyler, I warned you for a solid year, you cross me, and there will be consequences.”",
    "“We tried to poison you. We tried to poison you because you’re an insane, degenerate piece of filth, and you deserve to die.”",
    "“If you believe that there’s a hell, we’re pretty much already going there.”",
    "“Right now, what I need, is for you to climb down out of my ass. Can you do that? Will you do that for me, honey? Will you please, just once, get off my ass? You know? I’d appreciate it. I really would.”",
    "“Well, technically, chemistry is the study of matter, but I prefer to see it as the study of change.”",
    "“Today is the first day of the rest of your life.”",
    "“There are two sides to every story, always.”",
    "“There’s more than one kind of prison.”",
    "“Sometimes, I feel like I never actually make any of my own. Choices, I mean. My entire life, it just seems I never, you know, had a real say about any of it. Now this last one, cancer, all I have left is how I choose to approach this.'”",
    "“What is going on with me is not about some disease. It’s about choices. Choices that I have made, choices I stand by.”",
    "“You know I, I just think that things have a way of working themselves out.”",
    "“Sometimes, it feels better not to talk. At all. About anything. To anyone.”",
    "“Electrons—they change their energy levels. Molecules change their bonds. Elements—they combine and change into compounds. Well, that’s all of life, right? It’s the constant. It’s the cycle. It’s solution, dissolution, just over and over and over. It is growth, then decay, then transformation.”",
    "“See that watch? It’s a birthday present. The person who gave me this present wanted me dead too. Not that long ago, he pointed a gun right between my eyes, right here, and he threatened to kill me. He changed his mind about me, Skyler. And so will you.”",
    "“You think I came all this way just to let something as silly as lung cancer take me down? Not a chance. I’m not going anywhere.”",
    "“I’m saying that I lived too long. You want them to actually miss you. I truly believe there exists some combination of words. There must exist certain words in a certain specific order that can explain all of this, but with her, I just can’t ever seem to find them.”",
    "“It’s kind of funny. When I got my diagnosis, cancer, I said to myself, ‘Why me?’ And then, the other day, when I got the good news, I said the same thing.”",
    "“Name one thing in this world that is not negotiable.”",
    "“It can be done exactly how I want it. The only question is, are you the man to do it?”",
    "“It cannot be blind luck or some imaginary relative who saves us. No, I earned that money, me.”",
    "“I watched Jane die. I was there. And I watched her die. I watched her overdose and choke to death. I could have saved her. But I didn’t.”",
    "“Stay out of my territory.”",
    "“My name is Walter Hartwell White. I live at 308 Negra Arroyo Lane, Albuquerque, New Mexico, 871QUOTE_LINE To all law enforcement entities, this is not an admission of guilt. I am speaking to my family now. Skyler, you are the love of my life. I hope you know that. Walter Jr., you’re my big man. There are going to be some things that you’ll come to learn about me in the next few days, but just know that no matter how it may look, I only had you in my heart. Goodbye.”",
    "“Cheer up, beautiful people. This is where you get to make it right.”",
    "“All I can do is wait for the cancer to come back.”",
]
